name = "shortcut-mcp-worker"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[build]
command = "npm run build"

[vars]
# Public variables here

# Add KV storage for sessions if needed
# kv_namespaces = [
#   { binding = "SESSIONS", id = "xxxx", preview_id = "xxxx" }
# ]