name: Pipeline - MCP Server

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - mdthorpe/sc-307156/x-rollback-fake-oauth
      
jobs:
  build-docker:
    uses: ./.github/workflows/build_ecr_image.yml
    permissions:
      contents: read
      id-token: write

